### ISSUE TITLE
Separate pre-processing to a new script

### ISSUE THREAD

**Issue by vigneshRajakumar** [UBC-MDS/Movie_Selection#18]
- Handle bad data
- Handle nulls, if present
- save as csv

**Comment by anodaini** [comment]
While working on app.py, I noticed some things we could possibly do in the preprocessing script. (You don't have to act on these but I thought I'd write them here for us to eventually deal with them): 
- While working on the top 10 movies dataframe, if we want to keep the profit column, I was wondering if we should calculate the profit in the preprocessing file. 
- Also exploding the dataframe for studios and genres is currently in the app.py
- There are some repeated movie titles (there are some such as Dunkirk and Saving Private Ryan) that show up in the ranking dataframe.

**Comment by vigneshRajakumar** [comment]
Ill include the exploding in this file and add a profits column. 

The repeated rows is a strange one: they are repeated as a result of the exploding. For example:

```python
>>> movies[movies.title == 'Dunkirk']
          id    title  runtime     budget    revenue  vote_average  vote_count   genres       studios     profit
1002  374720  Dunkirk      107  100000000  519876949          4.11         282   Action  Warner Bros.  419876949
1002  374720  Dunkirk      107  100000000  519876949          4.11         282      War  Warner Bros.  419876949
1002  374720  Dunkirk      107  100000000  519876949          4.11         282    Drama  Warner Bros.  419876949
1002  374720  Dunkirk      107  100000000  519876949          4.11         282  History  Warner Bros.  419876949
1002  374720  Dunkirk      107  100000000  519876949          4.11         282   Action        Canal+  419876949
1002  374720  Dunkirk      107  100000000  519876949          4.11         282      War        Canal+  419876949
1002  374720  Dunkirk      107  100000000  519876949          4.11         282    Drama        Canal+  419876949
1002  374720  Dunkirk      107  100000000  519876949          4.11         282  History        Canal+  419876949
```

`Dunkirk` appears so many times because of the `genre` and `studio` explosions.

**Comment by athy9193** [comment]
I think it is find because we do not do summation computation on these. Moreover, after we filter by studio and genres, I would think the duplicate will not appear.

**Comment by anodaini** [comment]
Oh I see, that makes a lot of sense because we are not filtering by studio yet in our app.
