### ISSUE TITLE
"Peer" feedback M2

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/Movie_Selection#32]
Hello group 7, Sara here.
I am trying to make it big in the movie streaming business my company Bestflix (**IP theft!!**) and it looks like [your dashboard](https://movie-selection-app.herokuapp.com/) could help! I took your it for a spin and here are my thoughts:

- First off, great color selection, and stylish side bar! The motivations text in the sidebar and plot titles in the card boxes are also really effective.
- Could you align the cards over the plot with the same value? It seems like the are switched left right now.
- Oh and it would be useful if you would in clude that average (or median) value as a vertical line in your boxplots so that I could see easily which do better than the average, something like this https://altair-viz.github.io/gallery/bar_chart_with_mean_line.html
- Your table and scatter plot is taking up a lot of horzontal space, it would be easier to read them if they were next to each other like the boxplots
    - After this I think you can fit the entire app into one full page view with no need for scrollbars, that would look nice!
- And do you think you could add some additional controls to your data set? Something else we could filter on like, revenue rang, number of votes or such? I feel like there could be some complexity/functionality added.

I am definitely liking it overall and think this could be really useful for me moving forward!

**Comment by vigneshRajakumar** [comment]
Hi ~Joel~ Sara,

Thanks for the feedback! Summarizing:

- [x] Cards realignment #30 
- [x] Average and Median lines #34 
- [x] Horizontally Stack table and scatter plot #35 
- [x] Additional Controls #33

**Comment by joelostblom** [comment]
Looking good! I especially like your choice of plotly template in #33... https://github.com/plotly/plotly.py/pull/1864 :wink:

**Comment by vigneshRajakumar** [comment]
That's super cool! I honestly just picked the best looking one 😉
