### ISSUE TITLE
Could you use this optimized version of your GIF?

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/Movie_Selection#48]
Hey @vigneshRajakumar @anodaini @athy9193 @xudongyang2 ! Do you mind switching to this optimized versus of your gif? The dashboard showcase is having some performance degradation on Chrome from everyone's great gifs. This one is still pretty good quality and 2 MB instead of 8 MB.

![ezgif com-optimize (2)](https://user-images.githubusercontent.com/4560057/107170262-bc3a6b00-6974-11eb-903c-50db6590bba5.gif)

**Comment by athy9193** [comment]
Thank you so much, @joelostblom! This looks great! Sure we will definitely use this.

**Comment by joelostblom** [comment]
Thank you!!
